In [1]:
import numpy as np

In [8]:
arr = np.array([[2, 3, 4], [5, 2, 4], [6, 6, 7]])

In [12]:
arr.shape

(3, 3)

In [13]:
myarr = np.array([1.4, 1.5, 5.5, 6.7])

In [17]:
int_arr=myarr.astype(int)
int_arr

array([1, 1, 5, 6])

In [18]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [23]:
arr = np.array([10, 20, 30, 40, 50, 60])
yes = arr.reshape((2,3))
yes

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
mask = arr>30
mask

array([False, False, False,  True,  True,  True])