In [1]:
 import numpy as np
 import time
 # Python list
 size = 1_000_000
 list1 = list(range(size))
 list2 = list(range(size))
 start = time.time()
 result = [x + y for x, y in zip(list1, list2)]
 end = time.time()
print("Python list addition time:", end - start)
 # NumPy array
 arr1 = np.array(list1)
 arr2 = np.array(list2)
 start = time.time()
 result = arr1 + arr2  # Vectorized operation
 end = time.time()
 print("NumPy array addition time:", end - start)

Python list addition time: 0.09300971031188965
NumPy array addition time: 0.013038158416748047


In [2]:
 import numpy as np
 # Creating a 1D NumPy array
 arr1 = np.array([1, 2, 3, 4, 5])
 print(arr1)
 # Creating a 2D NumPy array
 arr2 = np.array([[1, 2, 3], [4, 5, 6]])
 print(arr2)
 # Checking type and shape
 print("Type:", type(arr1))
 print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [7]:
import numpy as np
import time

size = 1_000_000   # big size for real comparison

list1 = list(range(size))

start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print("Python list computation time:", end - start)

arr1 = np.array(list1)

start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print("NumPy array computation time:", end - start)


Python list computation time: 0.07481646537780762
NumPy array computation time: 0.0036318302154541016


In [9]:
import numpy as np

np.full((4,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [17]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [19]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape) # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)
print("Dimensions:", arr.ndim) # 2 → 2D array
# 6 → total elements
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # (2, 3)
reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)
 # [[1 2]
 #  [3 4]
 #  [5 6]]
flattened = arr.flatten() # Convert 2D → 1D
print(flattened) # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
